### ISSUE TITLE
Overwrite general settings option issue

### ISSUE THREAD

**Issue by lbrun22** [DanielRiera/estimated-delivery-woocommerce#57]
Hi,
In the product page of certain products, I would select the 'overwrite general settings' box. The delivery estimate changes would be applied. However, I found that over time, nearly all of the products that I had 'overwrite general settings' box applied, would lose this setting. The setting could last for 2-10 weeks but then the 'overwrite general settings' box would eventually untick itself?

Any ideas to what is causing this as I really like the plugin and would like to continue to use it.

Many thanks.

Louis

![overwrite general settings issue](https://github.com/DanielRiera/estimated-delivery-woocommerce/assets/155760061/2d9d7bb4-5d7e-4f30-83a5-2bc04f0e1e4c)

**Comment by DanielRiera** [comment]
Hi, sorry for the delay....I didn't get the notification Do you use any plugin to import products? 

This is caused by the import plugin deletes all the product metadata to update it. In the import plugin settings omit should allow you to omit certain product metadata, if so, omit all those starting with "_edw".
